services:
  app:
    image: ghcr.io/vnt87/puppeteeer-capture:latest
    ports:
      - "5432:3000"
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
      - PUPPETEER_ARGS=--no-sandbox,--disable-setuid-sandbox
