version: '3.8'
services:
  app:
    image: ghcr.io/vnt87/puppeteeer-capture:sha-1a9e996
    ports:
      - "5432:3000"
    volumes:
      - ./screenshots:/app/screenshots
    environment:
      - NODE_ENV=production
